### ISSUE TITLE
exception using layout

### ISSUE THREAD

**Issue by nageshs** [googlecodelabs/constraint-layout#1]
Exception using a specific layout

 Process: com.google.googleio, PID: 8100
                                                                   java.lang.NoClassDefFoundError: Failed resolution of: Ljava/awt/Rectangle;
                                                                       at android.support.constraint.solver.widgets.Guideline.<init>(Guideline.java:43)
                                                                       at android.support.constraint.ConstraintLayout.setChildrenConstraints(ConstraintLayout.java:128)
                                                                       at android.support.constraint.ConstraintLayout.updateHierarchy(ConstraintLayout.java:106)
                                                                       at android.support.constraint.ConstraintLayout.onFinishInflate(ConstraintLayout.java:87)
                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:867)
                                                                       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                                                                       at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:414)
                                                                       at android.app.Activity.setContentView(Activity.java:2424)
                                                                       at com.google.googleio.MainActivity.onCreate(MainActivity.java:25)
                                                                       at android.app.Activity.performCreate(Activity.java:6669)
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2578)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2686)
                                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1440)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)

-- layout file --
<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:layout_editor_absoluteX="0dp"
    tools:layout_editor_absoluteY="72dp"
    android:id="@+id/constraintLayout">

    <ImageView
        android:src="@drawable/singapore"
        android:layout_width="136dp"
        android:layout_height="139dp"
        tools:layout_editor_absoluteX="109dp"
        tools:layout_editor_absoluteY="100dp"
        android:id="@+id/imageView2"
        android:contentDescription="@string/dummy"
        android:scaleType="center"
        app:layout_constraintLeft_toLeftOf="@+id/constraintLayout"
        android:layout_marginStart="16dp"
        tools:layout_constraintLeft_creator="0"
        app:layout_constraintRight_toRightOf="@+id/constraintLayout"
        android:layout_marginEnd="16dp"
        tools:layout_constraintRight_creator="0"
        app:layout_constraintHorizontal_bias="0.22" />

    <android.support.constraint.Guideline
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:id="@+id/guideline"
        app:orientation="horizontal"
        tools:layout_editor_absoluteX="0dp"
        tools:layout_editor_absoluteY="20dp"
        app:relativeBegin="20dp" />

    <TextView
        android:text="TextViewTextViewTextViewTextViewTextView"
        android:layout_width="178dp"
        android:layout_height="90dp"
        tools:layout_editor_absoluteX="285dp"
        tools:layout_editor_absoluteY="118dp"
        android:id="@+id/textView4"
        app:layout_constraintLeft_toRightOf="@+id/imageView2"
        android:layout_marginStart="40dp"
        tools:layout_constraintLeft_creator="0"
        app:layout_constraintTop_toTopOf="@+id/imageView2"
        tools:layout_constraintTop_creator="0"
        app:layout_constraintBottom_toBottomOf="@+id/imageView2"
        tools:layout_constraintBottom_creator="0"
        app:layout_constraintVertical_bias="0.38" />

</android.support.constraint.ConstraintLayout>

**Comment by romainguy** [comment]
This is a known issue that we fixed today in the internal codebase. The next version of constraint-layout will have the fix. Thanks!
