### ISSUE TITLE
exception using layout

### ISSUE THREAD

**Issue by samuelhuahui** [googlecodelabs/constraint-layout#35]
java.lang.NoSuchMethodError: android.support.constraint.solver.widgets.ConstraintWidget.setHorizontalMatchStyle(III)V
	at android.support.constraint.ConstraintLayout.setChildrenConstraints(ConstraintLayout.java:853)
	at android.support.constraint.ConstraintLayout.updateHierarchy(ConstraintLayout.java:631)
	at android.support.constraint.ConstraintLayout.onMeasure_Original(ConstraintLayout.java:971)
	at android.support.constraint.ConstraintLayout.onMeasure(ConstraintLayout.java)
	at android.view.View.measure(View.java:22035)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6622)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:22035)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
	at android.view.View.measure(View.java:22035)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.measureView(RenderSessionImpl.java:590)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:343)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:384)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:193)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:547)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$3(RenderTask.java:681)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by aniketmj18** [comment]
I got this error message (I am using Android Studio):
Unexpected error while executing: am start -n "com.google.googleio/com.google.googleio.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Error while Launching activity

**Comment by liangxianshen** [comment]
It's the same problem

**Comment by MonStar1** [comment]
It's the same problem

**Comment by Jeromeer** [comment]
It's the same problem
